# Generated by Django 6.0.5 on 2026-06-01 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('patient_name', models.CharField(max_length=128)),
                ('time_label', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('soldier_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=64)),
                ('regiment', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('critical', 'Critical'), ('monitoring', 'Monitoring'), ('stable', 'Stable'), ('consultation', 'Consultation')], max_length=20)),
                ('altitude', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('spo2', models.IntegerField()),
                ('temp', models.FloatField()),
                ('fatigue', models.IntegerField()),
                ('stress', models.IntegerField()),
                ('location', models.CharField(max_length=128)),
                ('last_update_label', models.CharField(max_length=32)),
                ('respiration', models.IntegerField(default=16)),
                ('bp_systolic', models.IntegerField(default=120)),
                ('bp_diastolic', models.IntegerField(default=80)),
            ],
            options={
                'ordering': ['soldier_id'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secure_node', models.CharField(default='JOD-01', max_length=32)),
                ('uplink_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'System configuration',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('rank', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=128)),
                ('avatar_url', models.URLField(blank=True, max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=64, unique=True)),
                ('diagnosis', models.TextField()),
                ('notes', models.TextField()),
                ('hash_value', models.CharField(max_length=128)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.patient')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], max_length=20)),
                ('title', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('time_label', models.CharField(max_length=32)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.patient')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_position', models.PositiveIntegerField()),
                ('estimated_wait_minutes', models.PositiveIntegerField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_entry', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.patient')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatigue_prediction', models.IntegerField()),
                ('altitude_sickness_risk', models.IntegerField()),
                ('cardiac_risk', models.IntegerField()),
                ('stress_score', models.IntegerField()),
                ('readiness', models.IntegerField()),
                ('trends', models.JSONField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='core.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ReportOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='core.medicalreport')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(max_length=16)),
                ('event', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.medicalreport')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SensorStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('icon', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('syncing', 'Syncing'), ('pending', 'Pending')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_steps', to='core.patient')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrganDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_id', models.CharField(max_length=32)),
                ('data', models.JSONField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='core.patient')),
            ],
            options={
                'ordering': ['organ_id'],
                'unique_together': {('patient', 'organ_id')},
            },
        ),
    ]
