# Generated by Django 6.1.1 on 2026-09-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_activitylog_id_alter_aiinsight_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyalert",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="hub_key",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="source",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name="VitalSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64)),
                ("recorded_at", models.DateTimeField()),
                ("connected", models.BooleanField(default=True)),
                ("heart_rate", models.IntegerField(blank=True, null=True)),
                ("ecg_signal", models.CharField(blank=True, max_length=16)),
                ("leads_off", models.BooleanField(blank=True, null=True)),
                ("posture", models.CharField(blank=True, max_length=16)),
                ("lying_side", models.CharField(blank=True, max_length=8)),
                ("activity", models.CharField(blank=True, max_length=8)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_summaries",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-recorded_at"],
                        name="core_vitals_patient_77c939_idx",
                    )
                ],
            },
        ),
    ]
