# Generated by Django 6.1.1 on 2026-09-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_hub_sensor_summaries"),
    ]

    operations = [
        migrations.AddField(
            model_name="vitalsummary",
            name="replay",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
